"""Thin wrapper around the MinuteDock REST API (https://minutedock.com/api/v1).

Pure API access only - no business logic about what to sync or when (that's
app/core/web_filler.py). Every call authenticates with a Personal Access
Token as `Authorization: Bearer <token>`, generated by the user from their
own MinuteDock profile ("Manage Access Tokens") - see Settings in the GUI.

Contact/Project lookups (find_or_create_*) fetch a single unpaginated page
(the API's default limit is 500) and match by exact, case-insensitive,
trimmed name - not substring - to avoid e.g. "Smith" silently matching
"Smith Family Trust". This is a deliberate v1 limitation for a single small
engineering firm's account; a firm with more than ~500 contacts or projects
would need real pagination added to _get_all below.

Note: MinuteDock's own "New Project" web UI has a "Reference" text field,
but the Project schema has no equivalent (that's an Invoice-level field
instead) - there's nothing to send it to, so it's intentionally omitted here
rather than mapped to the wrong field.
"""

from __future__ import annotations

from typing import Any

import requests

from app.utils.logger import get_logger

logger = get_logger(__name__)

BASE_URL = "https://minutedock.com/api/v1"


class MinuteDockError(Exception):
    """Raised for any MinuteDock API failure - network, auth, or validation."""


def _request(method: str, token: str, path: str, **kwargs: Any) -> Any:
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/json"}
    try:
        response = requests.request(method, f"{BASE_URL}{path}", headers=headers, timeout=30, **kwargs)
    except requests.RequestException as exc:
        raise MinuteDockError(f"Could not reach MinuteDock: {exc}") from exc

    if response.status_code >= 400:
        message = response.text
        try:
            body = response.json()
            # The documented error shape is {"error": ..., "status": ...},
            # but at least one real response observed in testing instead used
            # {"status": "error", "message": ...} - check both rather than
            # trust the spec alone.
            message = body.get("error") or body.get("message") or message
        except ValueError:
            pass
        raise MinuteDockError(f"MinuteDock returned {response.status_code}: {message}")

    if not response.content:
        return None
    return response.json()


def test_connection(token: str) -> str:
    """Verify the token works, returning the active account's name."""
    account = _request("GET", token, "/accounts/current")
    return account.get("name", "")


def _find_by_name(items: list[dict[str, Any]], name: str) -> dict[str, Any] | None:
    target = name.strip().casefold()
    for item in items:
        if item.get("name", "").strip().casefold() == target:
            return item
    return None


def find_or_create_contact(token: str, name: str) -> dict[str, Any]:
    contacts = _request("GET", token, "/contacts", params={"active": "true"})
    existing = _find_by_name(contacts, name)
    if existing is not None:
        return existing

    return _request("POST", token, "/contacts", json={"contact": {"name": name, "active": True}})


def find_or_create_project(
    token: str,
    *,
    contact_id: str,
    name: str,
    billable: bool,
    default_rate_dollars: str | None,
) -> dict[str, Any]:
    projects = _request("GET", token, "/projects", params={"contact_id": contact_id, "active": "true"})
    existing = _find_by_name(projects, name)
    if existing is not None:
        return existing

    project: dict[str, Any] = {"name": name, "contact_id": contact_id, "billable": billable}
    if default_rate_dollars is not None:
        project["default_rate_dollars"] = default_rate_dollars

    return _request("POST", token, "/projects", json={"project": project})
